spring.application.name=VetCare

spring.jpa.open-in-view=true

spring.config.import=optional:file:.env[.properties]
spring.profiles.active=${SPRING_PROFILES_ACTIVE}

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true